# create a docker-compose.yml file
version: "2"
services:
  mongo_notifications:
    image: mongo
    volumes:
      - ./mongodata:/data
  web_notifications:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5010:3002"
    depends_on:
      - mongo_notifications
